config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '',path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'} ##Personalizando routes en authentication
  resources :porfolios, except:[:show]
  get 'angular-items', to: 'porfolios#angular'
  get 'porfolio/:id', to: 'porfolios#show', as: 'porfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do 
      get :toggle_status
      
    end
  end
 
 root to: 'pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: {draft: 0, published: 1}
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body

  belongs_to :topic
end

app/models/concerns/placeholder.rb
module Placeholder
  extend ActiveSupport::Concern

  def self.image_generator(height:, width:)
    "http://via.placeholder.com/#{height}x#{width}"
    
  end

end

app/models/porfolio.rb
class Porfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,  
                                reject_if: lambda { |attrs| attrs['name'].blank?  } #pasando hashes a un solo campo "name" pero puede ser a varios campos

  include Placeholder

  validates_presence_of :title, :body, :main_image, :thumb_image

  def self.angular
    where(subtitle: "Angular")
  end

  scope :ruby_on_rails_porfolios_items, -> {  where(subtitle: "Ruby on Rails")}

  after_initialize :set_defaults

    def set_defaults #metodo para poner por default la imagen en main y en thumb
           

      self.main_image ||=Placeholder.image_generator(height:'600', width:'400')
      self.thumb_image ||=Placeholder.image_generator(height:'350', width:'150')
    end

end

app/models/skill.rb
class Skill < ApplicationRecord
  include Placeholder

  validates_presence_of :title, :percent_utilized

    after_initialize :set_defaults

    def set_defaults #metodo para poner por default la imagen 
      self.badge ||=Placeholder.image_generator(height:'250', width:'250')
    end

end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :porfolio
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title

  has_many  :blogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name

  def first_name
    self.name.split.first
  end

  def last_name
    self.name.split.last

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

 ## before_action :configure_permitted_parameters, if: :devise_controller?
  ##def configure_permitted_parameters ##metodo para que acepte mas parametros en este caso name
 ##   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
 ##   devise_parameter_sanitizer.permit(:account_update, keys: [:name])
 ## end
  include DeviseWhitelist
  include SetSource
 
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
     elsif @blog.published?
      @blog.draft!
    end
    redirect_to blogs_url, notice: "Pos status has been updated"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern
  
  included do
      before_action :configure_permitted_parameters, if: :devise_controller?
        ##before_filter no funciona...
  end

  def configure_permitted_parameters ##metodo para que acepte mas parametros en este caso name
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/concerns/set_source.rb
module SetSource
  extend ActiveSupport::Concern
  included do
     before_action :set_source
  end
end

 

def set_source
    session[:source] = params[:q] if params[:q]
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Blog.all
    @skills = Skill.all
  end

  def about
  end

  def contact
  end
end

app/controllers/porfolios_controller.rb
class PorfoliosController < ApplicationController
  def index
    @portfolio_items = Porfolio.all
  end
  def angular
    @angular_portfolio_items = Porfolio.angular    
  end
  def new
    @portfolio_items = Porfolio.new
    3.times { @portfolio_items.technologies.build } #crea 3 items para agregar
  end

  def create
    @portfolio_items = Porfolio.new(porfolio_params)
    #se agrega technologies_attributes para guardar en la tabla realacionada a esta
    respond_to do |format|
      if @portfolio_items.save
        format.html { redirect_to porfolios_path, notice: 'Portfolio was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio_items }
      else
        format.html { render :new }
        format.json { render json: @portfolio_items.errors, status: :unprocessable_entity }
      end
    end
  end 
  def edit
    @portfolio_items = Porfolio.find(params[:id]) 
  end

  def update
    @portfolio_items = Porfolio.find(params[:id]) 
    respond_to do |format|
      if @portfolio_items.update(porfolio_params)
        format.html { redirect_to action: 'index', notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio_items }
      else
        format.html { render :edit }
        format.json { render json: @portfolio_items.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
        @portfolio_items = Porfolio.find(params[:id]) 
  end

  def destroy
    @portfolio_item = Porfolio.find(params[:id])
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to porfolios_path, notice: 'Blog was successfully destroyed.' }
    end
  end

  private 

  def porfolio_params
    params.require(:porfolio).permit(
      :title, 
      :subtitle, 
      :body, 
      technologies_attributes: [:name])
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/porfolios_helper.rb
module PorfoliosHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= link_to blog.status, toggle_status_blog_path(blog) %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit',  edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', :action => :index %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MorenusPortafolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
 
      <% if current_user%>
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        <%= link_to "Edit", edit_user_registration_path, method: :get %>
      <% else %>
        <%= link_to "Register",  new_user_registration_path, method: :get %>
        <%= link_to "Login", user_session_path, method: :get %>
      <% end %>  
       <%= yield %>
        
      <br>  

      <% if session[:source] %>
       <p>Thanks for visiting me from  <%= session[:source] %>
      <% end %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Hi <%= current_user.first_name if current_user %> </h1>
<p>Find me in app/views/pages/home.html.erb</p>

<h1>Blogs</h1>
<%= @posts.inspect %>

<h1>Skills</h1>
<%= @skills.inspect %>

app/views/porfolios/angular.html.erb
<h1>Angular Items</h1>

<a href="porfolios/new">Create new Item</a>

<%= link_to "Create new Item", new_porfolio_url %>



<%  @angular_portfolio_items.each do |porfolio_item| %>
  <p><%= link_to porfolio_item.title, porfolio_show_path(porfolio_item.id) %>  </p>
  <p><%=porfolio_item.subtitle %>  </p>
  <p><%=porfolio_item.body %>  </p>
  <%= image_tag porfolio_item.thumb_image  if !porfolio_item.thumb_image.nil? %> 
  <%#= image_tag porfolio_item.thumb_image  unless porfolio_item.thumb_image.nil? %> 
  <%= link_to "Edit", edit_porfolio_path(porfolio_item.id) %>
  <!-- <a href="/porfolios/<%= porfolio_item.id %>/edit">edit2</a> -->
  <%= link_to 'Destroy', porfolio_path(porfolio_item.id), method: :delete, data: { confirm: 'Are you sure?' } %>

<% end %>

app/views/porfolios/edit.html.erb
<h1>Edit this Portfolio Item</h1>

<%= form_for(@portfolio_items) do |form| %>
  
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/porfolios/index.html.erb
<h1>PorFolios Items</h1>

<a href="porfolios/new">Create new Item</a>

<%= link_to "Create new Item", new_porfolio_url %>



<%  @portfolio_items.each do |porfolio_item| %>
  <p><%= link_to porfolio_item.title, porfolio_show_path(porfolio_item.id) %>  </p>
  <p><%=porfolio_item.subtitle %>  </p>
  <p><%=porfolio_item.body %>  </p>
  <%= image_tag porfolio_item.thumb_image  if !porfolio_item.thumb_image.nil? %> 
  <%#= image_tag porfolio_item.thumb_image  unless porfolio_item.thumb_image.nil? %> 
  <%= link_to "Edit", edit_porfolio_path(porfolio_item.id) %>
  <!-- <a href="/porfolios/<%= porfolio_item.id %>/edit">edit2</a> -->
  <%= link_to 'Destroy', porfolio_path(porfolio_item.id), method: :delete, data: { confirm: 'Are you sure?' } %>

<% end %>

app/views/porfolios/new.html.erb
<h1>Create a new Portfolio Item</h1>

<%= form_for(@portfolio_items) do |form| %>
  
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <ul>
   <%= form.fields_for :technologies do |technology_form| %>
    <li>
      <%= technology_form.label :name %>
      <%= technology_form.text_field :name %>
    </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/porfolios/show.html.erb
<%= image_tag @portfolio_items.thumb_image if !@portfolio_items.thumb_image.nil? %>

<h1><%= @portfolio_items.title %></h1>

<em> <%= @portfolio_items.subtitle %> </em>

<em><%= @portfolio_items.body %></em>

<%= link_to 'Volver', :action => :index   %>
<%= link_to 'Edit', edit_porfolio_path%>

<h2>Technologies used: </h2>
<% @portfolio_items.technologies.each do |t| %>
  <ul>
    <li>
      <%= t.name %>
    </li>
  </ul>
<% end %>